#!/bin/bash
flags=""
case "$@" in
	*--*)
		for arg
		do
			shift
			case "$arg" in
				--) break;;
				*) flags="$flags $arg";;
			esac
		done;;
esac

for srcfile
do
	/bin/cpp -M -I. -D__GNUC__ $flags $srcfile 2>/dev/null
done

exit 0
